hw02 express
AntoninaTarasyuk/nodejs-homework-REST-API pull request #1
Opened 2022-11-01 12:22 UTC by AntoninaTarasyuk

2022-11-04 20:19 UTC, Eastvarga commented on models/contacts.js
> +  fs.writeFile(contactsPath, JSON.stringify(newData));
Забагато зайвих дій, є методи масивів в яких Ви повинні розібратись, Вам же на користь
const removeContact = async (contactId) => {
  const contacts = await listContacts();
  // const contactForRemove = await getContactById(contactId);
  let removedElement;
  const newData = contacts.filter((contact) => {
    if (contact.id === contactId) {
      removedElement = contact;
      return false;
    }
    return true;
  });
  fs.writeFile(contactsPath, JSON.stringify(newData));
  return removedElement;
};
Набагато простіше логіка може бути, спробуйте в ній розібратись.

2022-11-04 20:22 UTC, Eastvarga commented on models/contacts.js
> +  Object.assign(contactForUpdate, body);
Спробуйте знайти інший спосіб апдейту елементу,використовуючі метод масиву map()

2022-11-04 20:24 UTC, Eastvarga commented on routes/api/contacts.js
> +    res.status(200).json({ code: '200', message: 'Success', contacts });
json(contacts); достатньо для успішної відповіді code message зайві у випадках успішної відповіді

2022-11-04 20:25 UTC, Eastvarga requested changes
Є зауваження, треба їх усунути

2022-11-05 21:43 UTC, AntoninaTarasyuk commented on routes/api/contacts.js
> +    res.status(200).json({ code: '200', message: 'Success', contacts });
Це поправила

2022-11-05 21:44 UTC, AntoninaTarasyuk commented on models/contacts.js
> +  Object.assign(contactForUpdate, body);
Переробила, використовуючи map()

2022-11-05 22:12 UTC, AntoninaTarasyuk commented on models/contacts.js
> +  fs.writeFile(contactsPath, JSON.stringify(newData));
В мене була інша логіка :) Подумала, якщо вже є функція, яка знаходить контакт по id, то можна її використати.
Освіжила в своїй пам'яті метод filter(). Якщо колбек повертає false - елемент не додається в новий масив (виходить типу видалення), якщо true - елемент додається. В нашому випадку, якщо нема елемента, який задовольняє умові колбека - новий масив буде такий, як оригінальний.

2022-11-06 07:58 UTC, Eastvarga commented on routes/api/contacts.js
> +    res.status(200).json({ code: '200', message: 'Successfully removed', deletedContact });
тут теж треба прибрати code message

2022-11-06 07:58 UTC, Eastvarga commented on routes/api/contacts.js
> +    res.status(201).json({ code: '201', message: 'Created', newContact });
тут теж

2022-11-06 07:58 UTC, Eastvarga requested changes
Є недоопрацювання

2022-11-07 08:38 UTC, Eastvarga approved these changes

2022-11-07 08:38 UTC, merged